/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package dino;

import javafx.application .Application;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;
import javafx.stage.Window;
import window.ScreenController;


public class App extends Application {

    public void start(Stage stage) {
        try {
            Parent mainMenu = FXMLLoader.load(getClass().getClassLoader().getResource("mainMenu.fxml"));
            Parent play = FXMLLoader.load(getClass().getClassLoader().getResource("playField.fxml"));
            ScreenController screenController = ScreenController.getScreenController().init(stage);

            screenController.addScreen(ScreenController.GameScene.MAIN_MENU, new Scene(mainMenu));
            screenController.addScreen(ScreenController.GameScene.GAME_PLAY, new Scene(play));
            screenController.activate(ScreenController.GameScene.MAIN_MENU);
            stage.setTitle("Hello");
            stage.show();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public static void main(String[] args) {
        launch();
    }

}
