/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dino;

import window.Window;

public class App {

    public static void main(String[] args) {
        new Window().init().start();
    }
}
